version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: make
    volumes:
      - ./:/usr/src/app
    container_name: app-ts
    ports:
      - '8080:8080'
    command: npm run dev
  postgresql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "12345678"
    ports:
      - "5432:5432"
    volumes:
      - ./protgresql:/var/lib/postgresql/data
