version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: make
    volumes:
      - ./src:/usr/src/app/src
      - ./nodemon.json:/usr/src/app/nodemon.json
    container_name: app-ts
    ports:
      - '8080:8080'
    command: npm run dev
  postgresql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "12345678"
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data

volumes:
  postgresql:
