version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: make
    volumes:
      - ./src:/usr/src/app/src
      - ./nodemon.json:/usr/src/app/nodemon.json
    container_name: app-ts
    ports:
      - '8080:8080'
    depends_on:
      - postgresql
    command: npm run dev
    environment:
      - DB_HOST=postgresql://posfiap:posfiap2@postgresql:5432/posfiap
      - PORT=8080
      - ID_USUARIO_MP=216003967
      - ID_EXTERNO_CAIXA=POS001
      - ACCESS_TOKEN_MP=TEST-3863552458711300-062021-356aadeb2786f647d2cfeea6a6a3ab6a-216003967
      - URL_NOTIFICATION=https://lovely-loops-beg.tunnelapp.dev/pagamento/webhook
  postgresql:
    image: postgres
    environment:
      POSTGRES_USER: "posfiap"
      POSTGRES_PASSWORD: "posfiap2"
    volumes:
      - postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  

volumes:
  postgresql:
